/**
 * Trust-level derivation for Public Proof-of-Execution Report.
 *
 * Pure functions only — they read from run.metadata, receipt.receipt_json
 * (with the optional `transaction_context` we attach in receipt metadata),
 * and receipt.ai_summary. No side effects, no fetches.
 *
 * The goal is to make the difference between "mock fallback" and "live API
 * data" obvious to external readers, so a hackathon judge can tell a Demo
 * Mode report apart from a Live Mode report at a glance.
 */

import type { Receipt } from "@/types/receipt";
import type { Run } from "@/types/run";

export type TransactionDataSource =
  | "Mock Fallback"
  | "Explorer API"
  | "Manual Input"
  | "Unknown";

export type AIReportSource =
  | "Mock AI Report"
  | "Generated by GLM-5.1"
  | "Generated by AI Provider"
  | "Generated by Claude-compatible API"
  | "Not generated";

export type VerificationLevel =
  | "Demo Mode"
  | "Basic Verified"
  | "Explorer Verified";

export type ReceiptSource = "Generated by AgentTrace" | "Missing";

export type ReportMode = "Demo Mode" | "Live Mode" | "Mixed Mode";

export type TrustLevel = {
  transactionDataSource: TransactionDataSource;
  aiReportSource: AIReportSource;
  verificationLevel: VerificationLevel;
  receiptSource: ReceiptSource;
  reportMode: ReportMode;
  // Convenience flags for the UI:
  isTxMock: boolean;
  isAiMock: boolean;
  hasTransaction: boolean;
  hasReceipt: boolean;
  hasAiReport: boolean;
};

type TxContextLike = {
  is_mock?: boolean;
  data_source?: string;
  analysis_source?: string;
  chain?: string;
  tx_hash?: string;
  transaction_hash?: string;
} | null | undefined;

export function deriveTrustLevel(
  run: Run,
  receipt: Receipt | null,
  txContext: TxContextLike,
): TrustLevel {
  // ---- Transaction Data Source ----
  const txDataSource = computeTransactionDataSource(run, txContext);

  // ---- AI Report Source ----
  const aiSummary = receipt?.ai_summary ?? null;
  const aiReportSource = computeAIReportSource(aiSummary);

  // ---- Receipt Source ----
  const receiptSource: ReceiptSource = receipt?.receipt_hash
    ? "Generated by AgentTrace"
    : "Missing";

  // ---- Verification Level ----
  const verificationLevel = computeVerificationLevel(
    txDataSource,
    receiptSource,
  );

  // ---- Report Mode ----
  const reportMode = computeReportMode(txDataSource, aiReportSource);

  return {
    transactionDataSource: txDataSource,
    aiReportSource,
    verificationLevel,
    receiptSource,
    reportMode,
    isTxMock: txDataSource === "Mock Fallback",
    isAiMock: aiReportSource === "Mock AI Report",
    hasTransaction: txDataSource !== "Manual Input" && txDataSource !== "Unknown",
    hasReceipt: receiptSource === "Generated by AgentTrace",
    hasAiReport: aiReportSource !== "Not generated",
  };
}

// ---------------------------------------------------------------------------

function computeTransactionDataSource(
  run: Run,
  txContext: TxContextLike,
): TransactionDataSource {
  if (txContext) {
    const ds = (txContext.data_source ?? "").toLowerCase();
    const as = (txContext.analysis_source ?? "").toLowerCase();
    if (txContext.is_mock === true || ds.includes("mock") || as === "mock") {
      return "Mock Fallback";
    }
    if (
      ds.includes("explorer") ||
      as === "ai" ||
      as === "explorer" ||
      txContext.is_mock === false
    ) {
      return "Explorer API";
    }
  }

  // Fall back to run metadata when there's no embedded transaction_context.
  if (run.metadata?.generated_from_transaction === true) {
    const meta = run.metadata?.analysis_source as string | undefined;
    if (meta === "mock") return "Mock Fallback";
    if (meta === "ai") return "Explorer API";
    return "Mock Fallback";
  }

  // No transaction at all but the run exists → user wrote it manually.
  if (run.id) return "Manual Input";

  return "Unknown";
}

function computeAIReportSource(
  aiSummary: Receipt["ai_summary"] | null,
): AIReportSource {
  if (!aiSummary) return "Not generated";
  const source = (aiSummary.source as string | undefined)?.toLowerCase() ?? "";
  if (source === "mock") return "Mock AI Report";
  if (source === "z_ai" || source === "zai" || source === "z.ai") {
    const model = (aiSummary.model as string | undefined)?.toLowerCase() ?? "";
    if (model.includes("glm-5.1") || model === "" || model.includes("glm")) {
      return "Generated by GLM-5.1";
    }
    return "Generated by AI Provider";
  }
  if (source === "claude_compatible") return "Generated by Claude-compatible API";
  if (source === "ai" || source === "anthropic") return "Generated by AI Provider";
  return "Not generated";
}

function computeVerificationLevel(
  txDataSource: TransactionDataSource,
  receiptSource: ReceiptSource,
): VerificationLevel {
  if (txDataSource === "Mock Fallback") return "Demo Mode";
  if (txDataSource === "Explorer API") return "Explorer Verified";
  if (receiptSource === "Generated by AgentTrace") return "Basic Verified";
  return "Demo Mode";
}

function computeReportMode(
  txDataSource: TransactionDataSource,
  aiReportSource: AIReportSource,
): ReportMode {
  const txLive = txDataSource === "Explorer API";
  const txMock = txDataSource === "Mock Fallback";
  const aiLive =
    aiReportSource === "Generated by GLM-5.1" ||
    aiReportSource === "Generated by AI Provider" ||
    aiReportSource === "Generated by Claude-compatible API";
  const aiMock = aiReportSource === "Mock AI Report";

  // Both fully live.
  if (txLive && aiLive) return "Live Mode";
  // Both mock (or one mock and the other absent).
  if ((txMock || !txLive) && (aiMock || aiReportSource === "Not generated")) {
    if (txMock || aiMock) return "Demo Mode";
  }
  // Anything else with a live + mock mix.
  if ((txLive && (aiMock || aiReportSource === "Not generated")) ||
      ((txMock || txDataSource === "Manual Input") && aiLive)) {
    return "Mixed Mode";
  }
  return "Demo Mode";
}
